Prevent GCC 14 `0 is out of bounds` compilation error in `fill` function
Prevents the following kind of errors:
```
In function ‘constexpr typename __gnu_cxx::__enable_if<std::__is_byte<_Tp>::__value, void>::__type std::__fill_a1(_Tp*, _Tp*, const _Tp&) [with _Tp = unsigned char]’,
    inlined from ‘constexpr void std::__fill_a(_FIte, _FIte, const _Tp&) [with _FIte = unsigned char*; _Tp = unsigned char]’ at /usr/include/c++/14/bits/stl_algobase.h:998:21,
    inlined from ‘constexpr void std::fill(_ForwardIterator, _ForwardIterator, const _Tp&) [with _ForwardIterator = unsigned char*; _Tp = unsigned char]’ at /usr/include/c++/14/bits/stl_algobase.h:1029:20,
    inlined from ‘void mbgl::Image<Mode>::fill(uint8_t) [with mbgl::ImageAlphaMode Mode = mbgl::ImageAlphaMode::Exclusive]’ at /home/runner/work/maplibre-native/maplibre-native/source/include/mbgl/util/image.h
    inlined from ‘void mbgl::Image<Mode>::resize(mbgl::Size) [with mbgl::ImageAlphaMode Mode = mbgl::ImageAlphaMode::Exclusive]’ at /home/runner/work/maplibre-native/maplibre-native/source/include/mbgl/util/im
    inlined from ‘virtual void Image_Resize_Test::TestBody()’ at /home/runner/work/maplibre-native/maplibre-native/source/test/util/image.test.cpp:101:17:
/usr/include/c++/14/bits/stl_algobase.h:972:25: error: ‘void* __builtin_memset(void*, int, long unsigned int)’ offset 0 is out of the bounds [0, 0] [-Werror=array-bounds=]
  972 |         __builtin_memset(__first, static_cast<unsigned char>(__tmp), __len);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

While technically this error is a compiler bug, and could be suppressed with a pragma,
the changes in this commit adhere to a more basic principle:
If it is already known that an array has a length of 0,
then no program should try to fill it or copy into it.

Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>